### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mhtchong1989** [luisdias/CakePHP-Report-Manager-Plugin#16]
Version 4.4 says I can access the plugin via non-root URL. How can I do this? 

And second, after loading the plugin on this URL: localhost/app/report_manager/reports I can see that the design is basic CakePHP. If I am going to merge this plugin with my application (meaning, the plugin will have my application's design), will I have to transfer all the contents of the ReportManager plugin folder to my main app folder?

**Comment by luisdias** [comment]
Hi.

The 4.4 version only changed the default value of the firstLevel javascript variable. See the changes here:
https://github.com/luisdias/CakePHP-Report-Manager-Plugin/commit/5ca9c9d5844d8d27113bf225c35ec05101e139b1

No. Follow the instalation instructions in the plugin's main page (see the "Installation" section) 
https://github.com/luisdias/CakePHP-Report-Manager-Plugin

**Comment by mhtchong1989** [comment]
I did follow the installation procedure. What I meant was I want the UI design of the Report Manager to have the same UI as my application. Because if you access the localhost/app/report_manager/reports you get the default CakePHP layouts. 

So my question is: is there an easy way to change the UI of Reports Manager? Or do I have to manually change them one by one?

**Comment by luisdias** [comment]
No.  You have to manually change them one by one. But first, try to remove the css files reference from the .ctp files - see if the plugin "assumes" your main css files.

**Comment by mhtchong1989** [comment]
I see. Thanks! I will post here with the updates! :)
