### ISSUE TITLE
reports table not found

### ISSUE THREAD

**Issue by openprojdev** [luisdias/CakePHP-Report-Manager-Plugin#2]
Table reports for model Report was not found in datasource default 
cakePHP 2.0

**Comment by openprojdev** [comment]
```
CORE/Cake/Model/Model.php line 3398 → Model->setSource(string)
CORE/Cake/Model/Model.php line 1276 → Model->getDataSource()
CORE/Cake/View/Helper/FormHelper.php line 191 → Model->schema()
CORE/Cake/View/Helper/FormHelper.php line 444 → FormHelper->_introspectModel(string, string)
APP/Plugin/ReportManager/View/Reports/wizard.ctp line 30 → FormHelper->create(string, array)
CORE/Cake/View/View.php line 908 → include(string)
CORE/Cake/View/View.php line 872 → View->_evaluate(string, array)
CORE/Cake/View/View.php line 463 → View->_render(string)
CORE/Cake/Controller/Controller.php line 959 → View->render(null, null)
CORE/Cake/Routing/Dispatcher.php line 110 → Controller->render()
CORE/Cake/Routing/Dispatcher.php line 85 → Dispatcher->_invoke(ReportsController, CakeRequest, CakeResponse)
APP/webroot/index.php line 96 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

**Comment by luisdias** [comment]
The Report Manager has no model ( look at line 30 of the controller ),
it reads the application models.

Follow the instructions at the "Installation" section of the README document:

https://github.com/luisdias/CakePHP-Report-Manager-Plugin/blob/master/README.txt

2012/5/7 dnydev
reply@reply.github.com:

> Table reports for model Report was not found in datasource default
> cakePHP 2.0
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/luisdias/CakePHP-Report-Manager-Plugin/issues/2

## 

# 

# L.D.
