### ISSUE TITLE
Delete report, One to many option <Ajax Error>

### ISSUE THREAD

**Issue by jasonchua89** [luisdias/CakePHP-Report-Manager-Plugin#3]
Hi,

Thanks for this wonderful plugin.

I have a problem that I'm facing which is regarding the delete report function. When I select the report to delete with the drop down list, a confirmation dialog box appears asking if I am sure if I want to delete it. Then when I click "OK", <Ajax Error> appears. 

Another problem is when selecting a model for a new report. Once I select any model, the one to many option changes immediately to <Ajax Error> as well. 

Other parts of the plugin is working fine except these two problems. Not sure what went wrong. Please do help.

**Comment by luisdias** [comment]
It seems that it may be some conflict with jQuery. The plugin loads the libraries from Google in the following files: wizard.ctp and index.ctp. If you loaded elsewhere (perhaps different versions) in your application it can cause errors. 
Another possibility would be if you use another javascript library (prototype, dojo etc).

**Comment by jasonchua89** [comment]
I have loaded jquery and jquery-ui in default.ctp. Now I just tried removing the lines from wizard.ctp and index.ctp to remove loading of the libraries from Google. Still had an error. Added the lines back in but directed it to my the jquery saved in my js folder. Still had an error. Not sure what's wrong here. 

Any help would be great. 
Thanks

**Comment by luisdias** [comment]
If your application has non-root urls maybe the error cause. In this
case, try the version 0.4.4 which has this bug fix.

https://github.com/luisdias/CakePHP-Report-Manager-Plugin/zipball/v0.4.4

Otherwise look at your browser's programmer tools (F12 in IE and
Chrome) and analyse more deeply what is going on.

2012/5/29 jasonchua89
reply@reply.github.com:

> I have loaded jquery and jquery-ui in default.ctp. Now I just tried removing the lines from wizard.ctp and index.ctp to remove loading of the libraries from Google. Still had an error. Added the lines back in but directed it to my the jquery saved in my js folder. Still had an error. Not sure what's wrong here.
> 
> Any help would be great.
> Thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/luisdias/CakePHP-Report-Manager-Plugin/issues/3#issuecomment-5983177

## 

# 

# L.D.

**Comment by jasonchua89** [comment]
Works fantastic!! Thank you very much for that. This version must just have been uploaded today as I still had the 0.4.3 version that was just downloaded yesterday. Thank you for that. Appreciate your help. 

Cheers!
