### ISSUE TITLE
Non-onetomany Model Error

### ISSUE THREAD

**Issue by jasonchua89** [luisdias/CakePHP-Report-Manager-Plugin#4]
Hi, 

When loading the saved report, if it the model does not have a one to many option, it gives these errors at the bottom of the page for Step 1:

Notice (8): Undefined index: Event.20120531_020656.crp [APP\Plugin\ReportManager\View\Reports\wizard.ctp, line 105]
Warning (2): Invalid argument supplied for foreach() [APP\Plugin\ReportManager\View\Elements\fields_dnd.ctp, line 3]

and when clicking "Finish" at step 4, an empty report is generated.

But when loading a saved report that has a one to many model associated, it works fine with no problems at all.

I am running the latest version of this plugin.

Please help. Thanks

**Comment by luisdias** [comment]
Hi Jason

Try the new tag 0.4.5 with bugfix and tell me if it worked. Thank you for your collaboration.

https://github.com/luisdias/CakePHP-Report-Manager-Plugin/zipball/v0.4.5

**Comment by jasonchua89** [comment]
Thanks Luis. That worked. 

But I somehow stumbled upon another bug. If I delete one saved report, it deletes, and then when I try to delete another saved report right after it without refreshing the page, it does not delete anymore. The confirmation prompt appears, and when I click "OK", it appears as though the process is successful but the report is still available in the drop down list. 

If I refresh the page, I am able to delete a saved report again but the same problem persists with the subsequent saved reports.

**Comment by luisdias** [comment]
Hi Jason!

The name and id of the html select tag were incorrect defined after a delete.
I recreated the same tag. Let me know if it works. Best regards.

https://github.com/luisdias/CakePHP-Report-Manager-Plugin/zipball/v0.4.5

2012/6/6 jasonchua89
reply@reply.github.com:

> Thanks Luis. That worked.
> 
> But I somehow stumbled upon another bug. If I delete one saved report, it deletes, and then when I try to delete another saved report right after it without refreshing the page, it does not delete anymore. The confirmation prompt appears, and when I click "OK", it appears as though the process is successful but the report is still available in the drop down list.
> 
> If I refresh the page, I am able to delete a saved report again but the same problem persists with the subsequent saved reports.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/luisdias/CakePHP-Report-Manager-Plugin/issues/4#issuecomment-6149042

## 

# 

# L.D.

**Comment by jasonchua89** [comment]
Hi Luis.

Works brilliantly now!! 

Thank you soooooo much for your help. Appreciate it very much!
