### ISSUE TITLE
Different Button Design 

### ISSUE THREAD

**Issue by jasonchua89** [luisdias/CakePHP-Report-Manager-Plugin#5]
Hi Luis!

Thanks again for your help previously. However, I have stumbled upon a problem that I don't seem to be able to fix. The "new" and "load" buttons for the index page of the report manager are of different design. Not sure what the problem is. I have been going through all the files and their codes and the only change that I can find that is causing the problem is that you have changed the code from:

echo $this->Form->end(**('Load'));
to
echo $this->Form->submit(**('Load'),array('name'=>'load'));

in the index.ctp file.

This change solved the previous issue we had but seem to change the design of the button and am not sure what is missing/extra in the code that is causing this difference in design. 

Attached is the link to the screenshot to show you what I mean: http://i.imgur.com/vxeas.jpg 

I hope you can help take a look at this and change the "load" button to be the same design as the "new" button. 

Thank you once again.

**Comment by luisdias** [comment]
Hi Jason! I can't see the problem you described. To me, both buttons are equal ( they are regular submit buttons ). 
Have you checked the css file of your application? Maybe some style class is the cause of the problem.

Best Regards!

**Comment by jasonchua89** [comment]
Hi Luis. That's fine. It was a CSS thing. I thought it was something to do with the plugin. Dont worry! 

Thank you!
