### ISSUE TITLE
Check all/Uncheck all

### ISSUE THREAD

**Issue by jasonchua89** [luisdias/CakePHP-Report-Manager-Plugin#6]
Hi Luis, 

This is not really an issue but just something I hope you can implement into this plugin.

In step 1 (Select Fields) of the wizard, is it possible to implement check all/uncheck all buttons? This will be good especially if there are a lot of fields to go through and instead of unchecking all of them manually, clicking the button will uncheck everything. 

Hope you can implement this! 

Thanks.

**Comment by luisdias** [comment]
HI Jason.

The check/uncheck is already implemented. It works by clicking on the name
of each model (at Step 1) and affects its fields.

Best regards

Luis

2012/8/7 jasonchua89 notifications@github.com

> Hi Luis,
> 
> This is not really an issue but just something I hope you can implement
> into this plugin.
> 
> In step 1 (Select Fields) of the wizard, is it possible to implement check
> all/uncheck all buttons? This will be good especially if there are a lot of
> fields to go through and instead of unchecking all of them manually,
> clicking the button will uncheck everything.
> 
> Hope you can implement this!
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/luisdias/CakePHP-Report-Manager-Plugin/issues/6.

## 

# 

# L.D.

**Comment by jasonchua89** [comment]
Hi Luis,

I didnt realise it already has that function and it works that way! 

Thank you!
